.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. eacoin_qt test_eacoin_qt
clean: FORCE
	$(MAKE) -C .. eacoin_qt_clean test_eacoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_eacoin_qt_check
eacoin-qt eacoin-qt.exe: FORCE
	 $(MAKE) -C .. eacoin_qt
