.TH EACOIN-CLI "1" "June 2016" "eacoin-cli 0.12"
.SH NAME
eacoin-cli \- a remote procedure call client for EACoin Core. 
.SH SYNOPSIS
eacoin-cli [options] <command> [params] \- Send command to EACoin Core. 
.TP
eacoin-cli [options] help \- Asks EACoin Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the eacoin-cli program. eacoin-cli is an RPC client used to send commands to EACoin Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBeacoind\fP, \fBeacoin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
